apiVersion: v1
kind: ConfigMap
metadata:
  name: lnmp-conf
  namespace: testenv 
data:
  default.conf: |
    server {
      listen  80 default_server;
      #server_name _;
      root   /usr/share/nginx/html;
     
      location / {
       index index.html index.htm index.php;
       autoindex off;
       if (!-e $request_filename) {
              rewrite ^/(.*)  /index.php last;
         }
      }
      location ~ \.php(.*)$ {
       fastcgi_pass 127.0.0.1:9000;
       fastcgi_index index.php;
       fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
       include  fastcgi_params;
      }
    }

  www.conf: |
    [global]
 
    [www]
    user = www-data
    group = www-data
    listen = 0.0.0.0:9000
     
    pm = dynamic
    pm.max_children = 5
    pm.start_servers = 2
    pm.min_spare_servers = 1
    pm.max_spare_servers = 3
