apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  labels:
    app: test
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "nfs-client"
  mountOptions:
    - hard
  nfs:
    path: /home/work/nfs_share
    server: 172.16.x.x
